mongo:
  image: bitnami/mongodb:latest
  expose:
    - "27017"
  environment:
    MONGODB_DATABASE: csp
    MONGODB_USERNAME: csp
    MONGODB_PASSWORD: changethis
    MONGODB_ROOT_PASSWORD: definitelychangethis

sinatra:
  image: 4armed/csp-backend
  links:
    - mongo
  expose:
    - "4567"
  environment:
    RACK_ENV: production
    CSP_MONGODB_DB: csp
    CSP_MONGODB_HOST: mongo
    CSP_MONGODB_USER: csp
    CSP_MONGODB_PASSWORD: changethis

frontend:
  image: 4armed/nginx
  volumes:
    - ./certs:/etc/nginx/certs
    - ./conf.d:/etc/nginx/conf.d
    - ./sites-enabled:/etc/nginx/sites-enabled
  ports:
    - "80:80"
    - "443:443"
  links:
    - sinatra
